### ISSUE TITLE
Current search UX is problematic

### ISSUE THREAD

**Issue by aivuk** [fuzue/seasonalfood#57]
First, the search results covering all the app screen is problematic for a couple of reasons:

 - If there are not results, you do need to close the full page dialog to try again.
 - You loose what you have written.
 - The search results cover what you typed, removing the context from the user.
 
 It would be better if we just display the results as a slide down component, right below the menu bar and not remove the search input text.

**Comment by eduardoliron** [comment]
Returned the original dialog interface, improving layout integration.

As a suggestion, we could add the searched text on the dialog.

**Comment by eduardoliron** [comment]
Waiting for approval and merge.

**Comment by aivuk** [comment]
@eduardoliron you still loose what you have written when you do the search in your PR. Any idea in how hard it's to fix?
