### ISSUE TITLE
Don't remove menu button when clicking in a fruit/vegetable

### ISSUE THREAD

**Issue by aivuk** [fuzue/seasonalfood#59]
Currently when you click on a fruit or vegetable the top left menu icon turns in a left arrow, to be used as a back button. This is problematic because things like "About the App" or "Language selector" must be accessible anytime. Currently, the user needs to press back and then click on the menu icon. This problem is even worse if you consider sharing a link as https://fuzue.tech/seasonalfood/foodpage/clementine, because there will not be anywhere for a new user following the link a obvious place to get more information about the application.

**Comment by elenavolpato** [comment]
Fix the back function is more important ate this moment, right now we are using the history. and when you click on a link and then click on the back button it doesn't work.

**Comment by eduardoliron** [comment]
I have proposed a solution by adding a new bar on the layout. This is not optmal but a better solution should be applied on the app redesign that is close by.
